# numpy : 수학 및 과학 연산을 위한 파이썬 패키지



- [quick start](https://docs.scipy.org/doc/numpy/user/quickstart.html)

In [12]:
# import
import numpy as np

## 배열 구조 및 연산

In [2]:
# -- 난수를 통한 배열 생성
data = np.random.randn(2, 3)
print(data)

[[-0.6779345  -0.25727812 -0.41854148]
 [ 1.15813006  0.65313577  2.43457848]]


In [3]:
# -- 리스트를 통한 배열 생성
data1 = [6, 7, 5, 8, 0, 1]
print(data1)

arr1 = np.array(data1)
print(arr1)

[6, 7, 5, 8, 0, 1]
[6 7 5 8 0 1]


In [6]:
# -- 2차원 리스트를 통한 배열 생성
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

# -- array 구조 출력
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [7]:
# -- 0으로 채워진 배열 생성
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# -- 순번으로 채워진 배열 생성
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
# -- 다차원 배열 생성 및 계산
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr + arr)
print(arr * arr)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]


## n차 배열

In [13]:
# -- 다차원 배열 생성 및 조회

arr2d = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
print(arr2d)
print(arr2d[1])
print(arr2d[1][2])
print(arr2d[:2, 1:]) 

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[14 15 16]
16
[[12 13]
 [15 16]]


## 불리언 색인(Boolean Index)

In [22]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.random.randn(7, 4)

print(names)
print(data)

print(names == "Bob")

# Bob이 있는 행
print(data[names == "Bob"])  

# Bob이 있는 행의 0번째 열
print(data[names == "Bob", 0])  

# 배열의 OR 조건 Boolean 조회
mask = (names == "Bob") | (names == "Will")
print(mask)

# -- 조건에 따라 배열 값 변경 조회
data[data < 0] = 0
print(data)

data[names != "Joe"] = 7
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.3745358  -0.05986109 -0.21557318 -0.9964507 ]
 [ 0.03311585 -1.32213756 -0.40503748 -0.18817376]
 [-0.47289886 -0.64179045 -1.0439667  -0.67304288]
 [-0.18513289 -1.81611119  0.17939683 -0.13065029]
 [ 0.10329693  0.67474811  0.43462896 -0.48760961]
 [-1.09055409  0.36788935  0.52800059 -0.6093116 ]
 [ 0.04652844  1.15502409 -0.32940412  0.54398742]]
[ True False False  True False False False]
[[ 0.3745358  -0.05986109 -0.21557318 -0.9964507 ]
 [-0.18513289 -1.81611119  0.17939683 -0.13065029]]
[ 0.3745358  -0.18513289]
[ True False  True  True  True False False]
[[0.3745358  0.         0.         0.        ]
 [0.03311585 0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.17939683 0.        ]
 [0.10329693 0.67474811 0.43462896 0.        ]
 [0.         0.36788935 0.52800059 0.        ]
 [0.04652844 1.15502409 0.         0.54398742]]
[[7.         7.         7.         7.        ]
 [

## 피벗팅(pivoting) 및 배열 재조합

In [32]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

# 재조합
arr = np.arange(16)
print(arr)

arr = np.arange(16).reshape(2, 2, 4)
print(arr)

# 피벗팅
arr2 = arr.swapaxes(1, 2)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


## 배열 조회 조건 및 집계

In [37]:
arr = np.random.randn(4, 4)
print(arr)

# -- where를 이용한 조건 조회
print(np.where(arr > 0, 1, -1))
print(np.where((0 < arr) & (arr < 10), 2, -2))
print(np.where(np.logical_and(arr > 0, arr < 10), 3, -3))
print(np.where((0 < arr) & (arr < 10), arr, -4))

# -- 배열 집계
print(arr.mean())
print(np.mean(arr))

print(arr.sum())

#누적 sum
print(arr.cumsum())  

print(arr.min())
print(arr.max())

[[-0.19212155  0.0532545   0.13179275 -0.39032098]
 [ 0.75434506 -0.28967633  1.79807461 -0.16205765]
 [-0.46336151  1.30156942 -0.44315546  1.34015301]
 [-0.01722251  0.71354865 -0.90865297 -1.63535523]]
[[-1  1  1 -1]
 [ 1 -1  1 -1]
 [-1  1 -1  1]
 [-1  1 -1 -1]]
[[-2  2  2 -2]
 [ 2 -2  2 -2]
 [-2  2 -2  2]
 [-2  2 -2 -2]]
[[-3  3  3 -3]
 [ 3 -3  3 -3]
 [-3  3 -3  3]
 [-3  3 -3 -3]]
[[-4.          0.0532545   0.13179275 -4.        ]
 [ 0.75434506 -4.          1.79807461 -4.        ]
 [-4.          1.30156942 -4.          1.34015301]
 [-4.          0.71354865 -4.         -4.        ]]
0.09942586302824619
0.09942586302824619
1.590813808451939
[-0.19212155 -0.13886705 -0.0070743  -0.39739528  0.35694979  0.06727346
  1.86534807  1.70329042  1.23992891  2.54149833  2.09834287  3.43849588
  3.42127337  4.13482201  3.22616904  1.59081381]
-1.6353552327652012
1.7980746106566932


## 정렬 밀 중복제거

In [43]:
arr = np.random.randn(4, 3)
print(arr)

# -- 정렬
arr.sort(0)  # 열(column) 단위로 정렬
print(arr)

arr.sort(1)  # 행(row) 단위로 정렬
print(arr)


# 중복제거
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
print(np.unique(names))  

# 중복제거,1번지 값 출력.
print(np.unique(names)[1]) 

# 집합 - 중복 허용 X
print(set(names))\

[[-0.97851845  0.89183829  1.70421526]
 [ 1.21988562  0.25132006  0.52039845]
 [ 1.17300597  1.45972572 -1.5321827 ]
 [-0.59092242 -0.62767412 -1.5064985 ]]
[[-0.97851845 -0.62767412 -1.5321827 ]
 [-0.59092242  0.25132006 -1.5064985 ]
 [ 1.17300597  0.89183829  0.52039845]
 [ 1.21988562  1.45972572  1.70421526]]
[[-1.5321827  -0.97851845 -0.62767412]
 [-1.5064985  -0.59092242  0.25132006]
 [ 0.52039845  0.89183829  1.17300597]
 [ 1.21988562  1.45972572  1.70421526]]
['Bob' 'Joe' 'Will']
Joe
{'Bob', 'Will', 'Joe'}


## 선형대수(행렬 연산)

In [55]:

x = np.array([[1, 2], [3,4]])
y = np.array([[6, 3], [-1, 7]])

# 아마다르 곱
print(x * y)

#
print(x.dot(y))
print(y.dot(x))

# print(x - y)
# print(x + y)
# print(x / y)

# 전치행렬
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 3], [-1, 7], [8, 9]])

# -- 행렬 곱하기
print(x.dot(y))  # print(x*y)는 에러발생

# ????????
# inverting, 
from numpy.linalg import inv, qr

x = np.random.randn(5, 5)

# x.T : x의 전치행렬.
mat = x.T.dot(x)
print(inv(mat))
print(mat.dot(inv(mat)))


[[ 6  6]
 [-3 28]]
[[ 4 17]
 [14 37]]
[[15 24]
 [20 26]]
[[-5 -1]
 [ 4 -3]]
[[ 7  5]
 [ 2 11]]
[[ 0.16666667  0.66666667]
 [-3.          0.57142857]]
[[ 28  44]
 [ 67 101]]
[[ 24.62628986  -2.68728763 -14.25475254   1.34075913  -7.63324516]
 [ -2.68728763   0.68591912   1.1920517   -0.10199741   0.99508583]
 [-14.25475254   1.1920517    8.82350442  -0.64226637   4.07572936]
 [  1.34075913  -0.10199741  -0.64226637   0.51181581  -0.51665918]
 [ -7.63324516   0.99508583   4.07572936  -0.51665918   2.82012446]]
[[ 1.00000000e+00  6.24960412e-17  4.86125496e-15  1.08740285e-16
   5.52179754e-16]
 [-6.27977288e-15  1.00000000e+00  4.65285711e-15  1.15633074e-15
   4.36991713e-16]
 [-5.38871850e-15 -2.67057290e-15  1.00000000e+00  7.28121985e-16
  -2.50181826e-15]
 [ 7.97785042e-15  3.03022161e-16 -2.92979692e-16  1.00000000e+00
   1.15790035e-15]
 [-1.33370780e-14 -6.65750388e-16  3.11859570e-15 -4.19279464e-16
   1.00000000e+00]]


## 난수 생성

In [51]:
samples = np.random.normal(size=(3, 4))
print(samples)

samples = np.random.normal(size=(2, 2))
print(samples)

data = np.random.randn(2, 2)
print(data)

[[-0.20332112  1.13821622  0.63592742 -0.2794165 ]
 [ 0.65196752 -0.33643343  0.28486644 -1.37354187]
 [-0.13872017  0.21484061  0.30417265  0.63531792]]
[[ 0.74913282 -0.23398779]
 [-0.87683477  1.96147994]]
[[-0.06703827 -0.64003023]
 [-0.07411079  0.048337  ]]
